unique points
aliyun/aliyun-tsdb-java-sdk pull request #107
Opened 2021-02-18 03:32 UTC by cuiyuan

2021-02-18 04:09 UTC, xiaowing requested changes

2021-02-20 07:11 UTC, xiaowing approved these changes

2021-02-20 09:10 UTC, cuiyuan commented on src/test/java/com/aliyun/hitsdb/client/util/UniqueUtilTest.java
> +package com.aliyun.hitsdb.client.util;
```
mvn cobertura:cobertura -Dmaven.test.skip=false -Dtest=**/value/**.java
```
只会测试value下面的Test，而value/request和value/response下面有更多的Test并没有跑到

这个本质上是travis ci的使用有问题，不能因为要迁就这种使用方式去改变代码的路径。

2021-02-20 09:36 UTC, JohnnyJie commented
是否应该Config里面增加配置项来控制做不做去重，对云上用户去重没有意义

2021-02-20 09:49 UTC, cuiyuan commented
> 是否应该Config里面增加配置项来控制做不做去重，对云上用户去重没有意义

本来就有这个计划，还在开发

2021-02-22 04:04 UTC, cuiyuan commented
默认配置不去重，如果需要启用去重, 需要在配置中开启deduplicationEnable()
```java
		TSDBConfig config = TSDBConfig
				.address("127.0.0.1", 8242)
				.deduplicationEnable()
				.config();

		TSDB tsdb = TSDBClientFactory.connect(config);
```

2021-02-23 02:00 UTC, merged