support set header for client & add fatal list for Lindorm TSDB
aliyun/aliyun-tsdb-java-sdk pull request #122
Opened 2021-05-17 08:54 UTC by JohnnyJie

* Lindorm TSDB测试需要设置header（租户信息），目前是单独发snapshot版本用于测试，相关功能合入主线就不用未来每次测试SDK相关功能都打一个snapshot
* Lindorm TSDB支持返回fatal字段，但是目前SDK里对于400，500错误是直接抛异常，所以实际200的解析不会带出该字段

2021-05-19 08:32 UTC, xiaowing commented
新加的API从功能角度无法理解...

2021-05-19 08:32 UTC, xiaowing commented on src/main/java/com/aliyun/hitsdb/client/BalTSDBClient.java
> +    public void setHeaderParamsMap(Map<String, String> headerParamsMap) {
setHeader是一个比较内部的操作，不应该作为TSDB SDK层面直接透传出来

2021-06-09 03:35 UTC, JohnnyJie commented on src/main/java/com/aliyun/hitsdb/client/BalTSDBClient.java
> +    public void setHeaderParamsMap(Map<String, String> headerParamsMap) {
已经移除

2021-06-09 03:38 UTC, xiaowing requested changes

2021-06-22 08:17 UTC, JohnnyJie commented on src/main/java/com/aliyun/hitsdb/client/HiTSDBConfig.java
> +        public Builder basicAuth(String instanceId, String tsdbUser, String basicPwd) {
已经还原

2021-06-22 11:38 UTC, xiaowing approved these changes

2021-06-22 11:38 UTC, merged