support tags operation for super tag mode
aliyun/aliyun-tsdb-java-sdk pull request #125
Opened 2021-06-07 02:26 UTC by JohnnyJie

Implement tagsAdd, tagsShow, tagsRemove method for super-tag  tags operation.

2021-06-09 03:38 UTC, xiaowing requested changes

2021-06-09 03:38 UTC, xiaowing commented on src/main/java/com/aliyun/hitsdb/client/value/response/TagsShowResult.java
> +public class TagsShowResult extends Result {
本质上`TagsShowResult`和`TagsRemoveInfo`是完全一样的数据结构.

这几个请求、响应的报文的封装实现能否考虑抽象和复用

2021-06-09 03:38 UTC, xiaowing commented on src/main/java/com/aliyun/hitsdb/client/IotClient.java
> +    public IotClient(Config config) throws HttpClientInitException {
`IoTClient` 作为 `TSDBClient`的一种特例形态，建议采用下述设计

1. 实例化时并非单纯地创建对象，而是在实例化时同时根据config的内容校验一下TSDB服务端的模式，模式符合要求时才允许对象成功创建
2. `tagsAdd()`, `tagsShow()`, `tagsRemove()` 是`IoTClient`的特有方法，要调用这几个方法时不能基于TSDB接口调用，必须是显式地通过 `IoTClient`对象调用。这一设计思路可参见PostgreSQL JDBC Driver对于一些特有功能接口的设计实现。

2021-06-09 03:49 UTC, JohnnyJie commented on src/main/java/com/aliyun/hitsdb/client/IotClient.java
> +    public IotClient(Config config) throws HttpClientInitException {
目前sdk没有在config支持是否是iot实例

2021-06-09 03:53 UTC, JohnnyJie commented on src/main/java/com/aliyun/hitsdb/client/TSDB.java
> +    TagsAddResult tagsAdd(TagsAddInfo tagsAddInfo);
已从TSDB接口移除

2021-06-17 11:31 UTC, xiaowing approved these changes

2021-06-17 11:32 UTC, merged